### Variables
@baseUrl = http://localhost:3000/v1
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxOWM2ZmZhNTExNTcxNzZiOGQ2NDgzOWRiNmRkYmM0IiwiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwibm9tYnJlIjoiSnVhbiBQZXJleiIsInJvbCI6ImNsaWVudGUiLCJpYXQiOjE3NzE1NDEwNjksImV4cCI6MTc3MjQ0MTA2OSwiaXNzIjoiUG9ydGFmb2xpb09ubGluZVJlYWN0LTIwMjUwMTAxLURldmVsb3AifQ.NXajyhtumC42411Fo06HMjd3fBw359EGc0Q7o4hN6Og
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxOWM2ZmZhNTExNTcxNzZiOGQ2NDgzOWRiNmRkYmM0IiwiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwibm9tYnJlIjoiSnVhbiBQZXJleiIsInJvbCI6ImNsaWVudGUiLCJpYXQiOjE3NzE1NDEwNjksImV4cCI6MTk0NDM0MTA2OSwiaXNzIjoiUG9ydGFmb2xpb09ubGluZVJlYWN0LTIwMjUwMTAxLURldmVsb3AifQ.-u0i096cdw3bX3Ga7YvjbzXcqarHvvg8VghoQNFdGgQ

### Login
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password123"
}

### Refrescar Token
POST {{baseUrl}}/refrescar-token
Content-Type: application/json
Cookie: refreshToken={{refreshToken}}

### Buscar Usuario por Email
POST {{baseUrl}}/buscar-usuario-por-email
Content-Type: application/json
Cookie: accessToken={{accessToken}}
Cookie: refreshToken={{refreshToken}}

{
  "email": "test@example.com"
}

### Crear Cuenta Usuario
POST {{baseUrl}}/crear-cuenta-usuario
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password123",
  "nombres": "Juan",
  "apellidos": "Perez"
}
